apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: pzoli77/mydevcontainer:1.0 #gradle:jdk17
    imagePullPolicy: Always
    name: ubuntu
    volumeMounts:
      - mountPath: "/home/pzoli/development"
        name: devroot
  restartPolicy: Always
  volumes:
  - name: devroot
    hostPath:
      path: /home/pzoli/development/volumes/devroot
